ecomerce_home:
  path: /
  controller: App\Controller\MainController::index

ecomerce_order_api:
  path: /api/order/request
  controller: App\Controller\MainController::orderRequest

ecommerce_order_status:
  path: /order/status
  controller: App\Controller\MainController::orderStatus
